#!/bin/bash
xrandr --output eDP1 --mode 1366x768 --pos 597x1080 --rotate normal --output DP1 --off --output HDMI1 --primary --mode 2560x1080 --pos 0x0 --rotate normal --output HDMI2 --off --output VIRTUAL1 --off

