[colors.primary]
background = "#000000"
foreground = "#8ae234"

[colors.cursor]
cursor = "#c7c7c7"
text = "#feffff"

[colors.normal]
black = "#000000"
blue = "#0225c7"
cyan = "#00c5c7"
green = "#00c200"
magenta = "#c930c7"
red = "#c91b00"
white = "#c7c7c7"
yellow = "#c7c400"

[colors.bright]
black = "#676767"
blue = "#6871ff"
cyan = "#5ffdff"
green = "#5ff967"
magenta = "#ff76ff"
red = "#ff6d67"
white = "#feffff"
yellow = "#fefb67"
