window:
  padding:
    x: 5
    y: 5
  decorations: buttonless
background_opacity: 0.95
draw_bold_text_with_bright_colors: true

font:
  normal:
    family: MesloLGS NF
    style: Regular
  bold:
    family: MesloLGS NF
    style: Bold
  italic:
    family: MesloLGS NF
    style: Italic
  size: 12.0
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0
  # use_thin_strokes: true

key_bindings:
  - { key: Left,     mods: Alt,     chars: "\x1bb"                       } # Skip word left
  - { key: Right,    mods: Alt,     chars: "\x1bf"                       } # Skip word right

#######################################
##      START OF COLOR SCHEMES       ##
#######################################
schemes:
  ### Doom One ###
  doom-one: &doom-one
    primary:
      background: '#282c34'
      foreground: '#bbc2cf'
    cursor:
      text: CellBackground
      cursor: '#528bff'
    selection:
      text: CellForeground
      background: '#3e4451'
    normal:
      black:   '#1c1f24'
      red:     '#ff6c6b'
      green:   '#98be65'
      yellow:  '#da8548'
      blue:    '#51afef'
      magenta: '#c678dd'
      cyan:    '#5699af'
      white:   '#202328'
    bright:
      black:   '#5b6268'
      red:     '#da8548'
      green:   '#4db5bd'
      yellow:  '#ecbe7b'
      blue:    '#3071db'   # This is 2257a0 in Doom Emacs but I lightened it.
      magenta: '#a9a1e1'
      cyan:    '#46d9ff'
      white:   '#dfdfdf'

  ### Solarized Dark ###
  solarized-dark: &solarized-dark
    # Default colors
    primary:
      background: '#002b36' # base03
      foreground: '#839496' # base0

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text:   '#002b36' # base03
      cursor: '#839496' # base0

    # Normal colors
    normal:
      black:   '#073642' # base02
      red:     '#dc322f' # red
      green:   '#859900' # green
      yellow:  '#b58900' # yellow
      blue:    '#268bd2' # blue
      magenta: '#d33682' # magenta
      cyan:    '#2aa198' # cyan
      white:   '#eee8d5' # base2

    # Bright colors
    bright:
      black:   '#002b36' # base03
      red:     '#cb4b16' # orange
      green:   '#586e75' # base01
      yellow:  '#657b83' # base00
      blue:    '#839496' # base0
      magenta: '#6c71c4' # violet
      cyan:    '#93a1a1' # base1
      white:   '#fdf6e3' # base3

  ### iTerm2 szmktk ###
  iterm2-szmktk: &iterm2-szmktk
    # Default colors
    primary:
      background: '#000000'
      # foreground: '#c7c7c7'  # default
      foreground: '#8ae234'

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '#feffff'
      cursor: '#c7c7c7'

    # Normal colors
    normal:
      black:   '#000000'
      red:     '#c91b00'
      green:   '#00c200'
      yellow:  '#c7c400'
      blue:    '#0225c7'
      magenta: '#c930c7'
      cyan:    '#00c5c7'
      white:   '#c7c7c7'

    # Bright colors
    bright:
      black:   '#676767'
      red:     '#ff6d67'
      green:   '#5ff967'
      yellow:  '#fefb67'
      blue:    '#6871ff'
      magenta: '#ff76ff'
      cyan:    '#5ffdff'
      white:   '#feffff'

######################################################################
## SET THEME: Choose ONE color scheme from those in the above list. ##
## ###################################################################
# Available themes are:
# colors: *doom-one
# colors: *solarized-dark
colors: *iterm2-szmktk

#######################################
##       END OF COLOR SCHEMES        ##
#######################################
